apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: user7-dotnet-app-
spec:
  params:
    - name: GIT_URL
      value: "https://github.com/ben135vak/dotnet-app"
    - name: REGISTRY
      value: ben135vak
    - name: IMAGE_NAME
      value: dotnet-app
    - name: IMAGE_TAG
      value: v0
    - value: user7-application
  pipelineRef:
    name: user7-dotnet-app
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: storage
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 150Mi
          volumeMode: Filesystem
